usr/sbin/NetworkManager
usr/bin/nm-online
usr/bin/nmcli
usr/bin/nmtui*
usr/lib/NetworkManager/nm-dhcp-helper
usr/lib/NetworkManager/nm-iface-helper
usr/lib/NetworkManager/nm-dispatcher
usr/lib/NetworkManager/nm-initrd-generator
usr/lib/*/NetworkManager/*/libnm-settings-plugin-ifupdown.so
usr/lib/*/NetworkManager/*/libnm-device-plugin-*.so
usr/lib/*/NetworkManager/*/libnm-ppp-plugin.so
usr/lib/*/NetworkManager/*/libnm-wwan.so
usr/lib/pppd/*/*.so
usr/share/locale/
usr/share/man/
usr/share/dbus-1/system-services/
usr/share/dbus-1/system.d/org.freedesktop.NetworkManager.conf
usr/share/dbus-1/system.d/nm-dispatcher.conf
usr/share/polkit-1/
usr/share/bash-completion/
etc/NetworkManager/dispatcher.d/
lib/udev/rules.d/*.rules
lib/systemd/system/NetworkManager.service
lib/systemd/system/NetworkManager-dispatcher.service
lib/systemd/system/NetworkManager-wait-online.service
debian/NetworkManager.conf etc/NetworkManager/
debian/org.freedesktop.NetworkManager.pkla var/lib/polkit-1/localauthority/10-vendor.d/
debian/60-network-manager.rules usr/share/polkit-1/rules.d/
debian/01-ifupdown etc/NetworkManager/dispatcher.d/
